### ISSUE TITLE
Landing Page For Events

### ISSUE THREAD

**Issue by mayank3810** [7saikat7/Hac_2021_special#21]
Create a frontend webpage for different types of events.

**Comment by mayank3810** [comment]
Hi,
Would you mind assigning this to me

**Comment by 7saikat7** [comment]
sorry was busy in some projects u can work on or directly send me pr

**Comment by 7saikat7** [comment]
you  can start working

**Comment by mayank3810** [comment]
Okay, I will submit a PR as soon as it is complete.

**Comment by rohitdubey1352** [comment]
Hello, Sir, I have developed An Event page Hope u Like it and add the Hacktoberfest2021 tag on me : )
https://github.com/7saikat7/Hac_2021_special/pull/27
